# 
# Unless explicitly acquired and licensed from Licensor under another license, the contents of
# this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
# versions as allowed by the RPL, and You may not copy or use this file in either source code
# or executable form, except in compliance with the terms and conditions of the RPL
#
# All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
# WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
# WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
# governing rights and limitations under the RPL.
#
# http://opensource.org/licenses/RPL-1.5
#
# Copyright 2012-2016 Open Justice Broker Consortium
# 

# Docker Compose file that brings up the analytics database, saiku and dashboards.  
# To run:  docker-compose -f analytics-compose.yaml up -d
# After running this file, you can browse to:
# http://localhost/dashboards/crisis-incidents-dashboard.html
# http://localhost/dashboards/jail-booking-dashboard.html
# http://localhost/saiku-ui

version: '3'

networks:
  ojbc_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.2.0/24

services:

 httpd-proxy:
   container_name: httpd-proxy
   image: ojbc/httpd-proxy
   ports:
      - "80:80"
   networks:
    - ojbc_nw

 analytics-db:
   container_name: analytics-db
   image: ojbc/analytics-db
   networks:
    - ojbc_nw 

 saiku:
   container_name: saiku
   image: ojbc/analytics-saiku
   networks:
    - ojbc_nw  

 dashboards:
   container_name: dashboards
   image: ojbc/analytics-dashboards

   networks:
    - ojbc_nw  
