# 
# Unless explicitly acquired and licensed from Licensor under another license, the contents of
# this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
# versions as allowed by the RPL, and You may not copy or use this file in either source code
# or executable form, except in compliance with the terms and conditions of the RPL
#
# All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
# WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
# WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
# governing rights and limitations under the RPL.
#
# http://opensource.org/licenses/RPL-1.5
#
# Copyright 2012-2016 Open Justice Broker Consortium
# 

# Docker Compose file that runs all the containers involved in an OJB Portal demo
# To run:  docker-compose -f apache-backend-proxy-demo.yaml up -d
#
# Test Port 80
# http://example-host/app1/
# http://example-host/app2/
#
# Test Port 443
# https://example-secure-host/app1/
# https://example-secure-host/app2/

version: '3'

networks:
  ojbc_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.18.2.0/24

services:

 apache-backend-proxy-demo:
  container_name: apache-proxy
  image: ojbc/apache-backend-proxy-demo
  build: ./apache-backend-proxy-demo
  networks:
   - ojbc_nw
  ports: 
   - "80:80"
   - "443:443"   