# 
# Unless explicitly acquired and licensed from Licensor under another license, the contents of
# this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
# versions as allowed by the RPL, and You may not copy or use this file in either source code
# or executable form, except in compliance with the terms and conditions of the RPL
#
# All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
# WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
# WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
# governing rights and limitations under the RPL.
#
# http://opensource.org/licenses/RPL-1.5
#
# Copyright 2012-2016 Open Justice Broker Consortium
# 

# Docker Compose file that runs all the containers involved in an OJB Portal demo
# To run:  docker-compose -f demostate-test-portal-compose.yaml up -d
# Then navigate to: https://localhost/ojb-web-portal/
# User id / password is: demouser1 password

version: '3'

networks:
  ojbc_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.18.2.0/24

services:

 karaf-demostate-test:
  container_name: karaf-demostate
  build: karaf-demostate-test
  networks:
   - ojbc_nw 
  ports: 
   - "8443:8443"

 apacheds:
  container_name: apacheds
  image: ojbc/apacheds
  networks:
   - ojbc_nw  
  
 idp:
  container_name: idp
  build: idp
  networks:
   - ojbc_nw  
  
 samlds:
  container_name: samlds
  image: ojbc/samlds
  networks:
   - ojbc_nw   
  
 portal:
  container_name: portal
  build: portal
  networks:
   - ojbc_nw
  ports: 
   - "443:443"
  
 ojb-web-util:
  container_name: tomcat
  image: ojbc/ojb-web-util
  networks:
   - ojbc_nw    
  
 ojb-web-portal:
  container_name: ojb-web-portal
  build: ojb-web-portal
  networks:
   - ojbc_nw    
 
  