#!/bin/bash

# Shell script to produce a little string with the current docker-machine name and its IP address, or empty string if nothing
# To create a bash prompt with this in it, copy this script to a directory on your PATH (e.g., /usr/local/bin) and set the PS1 variable in your .bash_login file (in your home directory), for example:
# export PS1="\D{%d} \A \u \w [\$(docker-machine-info)]\n\$: "

if [ "$DOCKER_MACHINE_NAME" != "" ] && docker-machine status $DOCKER_MACHINE_NAME | grep -q Running
then
  echo $DOCKER_MACHINE_NAME@$(docker-machine ip $DOCKER_MACHINE_NAME)
else
  echo ""
fi