# Docker Compose file to test docker health checks
# To run in Docker Swarm:  
# 1.  docker swarm init
# 2.  docker stack deploy --compose-file healthcheck-demo.yaml healthdemo
# To run in normal Docker:
# docker-compose -f healthcheck-demo.yaml up -d

version: '3'

services:

  portal:
    container_name: portal
    image: ojbc/portal
    deploy:
      replicas: 1
    networks:
       - overlay
    ports: 
      - "443:443"
    healthcheck:
      test: curl -f -k https://localhost/health-check.html
      interval: 10s
      timeout: 10s
      retries: 1
#      start_period: 40s
       
networks:
  overlay:
