# Docker Compose file to test docker health checks
# To run:  docker stack deploy --compose-file healthcheck-demo.yaml healthdemo

version: '3'

services:

  ojb-web-util:
    container_name: ojb-web-util
    image: ojbc/ojb-web-util
    networks:
      - overlay
  portal:
    container_name: portal
    image: ojbc/portal-health
    deploy:
      replicas: 1
    networks:
       - overlay
    ports: 
      - "443:443"
    healthcheck:
     # in order for Docker to revive an unhealthy container you must be running in swarm mode: docker swarm init
      test: curl -f -k https://localhost/health-check.html || exit 1
      interval: 10s
      timeout: 10s
      retries: 1
#      start_period: 40s        
networks:
  overlay: