# Docker Compose file that brings up containers necessary for OJBC demostate environment
# To run:  docker-compose -f ojbc-demostate.yaml up -d
version: '3'

networks:
  ojbc_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      -
       subnet: 172.18.0.0/16

services:

  portal:
    container_name: portal
    image: ojbc/portal
    networks:
      ojbc_nw:    
    ports: 
      - "443:443"

  samlds:
    container_name: samlds
    image: ojbc/samlds
    networks:
      ojbc_nw:
      
      
  apacheds:
    container_name: apacheds
    image: ojbc/apacheds
    networks:
      ojbc_nw:
  
  idp:
    container_name: idp
    image: ojbc/idp
    depends_on:
      - apacheds
    networks:
      ojbc_nw:    

  ojb-web-util:
    container_name: ojb-web-util
    image: ojbc/ojb-web-util
    networks:
      ojbc_nw: 
      
  analytics-db:
    container_name: analytics-db
    image: ojbc/analytics-db
    networks:
      ojbc_nw:
      
  analytics-saiku:
    container_name: saiku
    image: ojbc/analytics-saiku
    depends_on:
      - analytics-db
    networks:
      ojbc_nw:
      
   
  analytics-dashboards:
    container_name: dashboards
    image: ojbc/analytics-dashboards
    depends_on:
      - analytics-db
    networks:
      ojbc_nw:
 
  