# 
# Unless explicitly acquired and licensed from Licensor under another license, the contents of
# this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
# versions as allowed by the RPL, and You may not copy or use this file in either source code
# or executable form, except in compliance with the terms and conditions of the RPL
#
# All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
# WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
# WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
# governing rights and limitations under the RPL.
#
# http://opensource.org/licenses/RPL-1.5
#
# Copyright 2012-2016 Open Justice Broker Consortium
# 

# Docker Compose file that creates SAML sandbox environment
# To run:  docker-compose -f saml-sandbox-compose.yaml up -d
# Then visit https://localhost/portal/ojb-web-util/index.jsp
# You will prompted for a userid/password and can enter: demouser1 and password

version: '3'

networks:
  ojbc_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.2.0/24

services:

 apacheds:
  container_name: apacheds
  image: ojbc/apacheds
  networks:
    - ojbc_nw   
  
 idp:
  container_name: idp
  image: ojbc/idp
  networks:
    - ojbc_nw   
  
 samlds:
  container_name: samlds
  image: ojbc/samlds
  networks:
    - ojbc_nw  
  
 portal:
  container_name: portal
  image: ojbc/portal
  networks:
    - ojbc_nw   
  
 ojb-web-util:
  container_name: tomcat
  image: ojbc/ojb-web-util
  networks:
    - ojbc_nw  
  