# Docker Compose file that brings up containers necessary for demo.search.org which includes CCH demo stuff
# To run:  docker-compose -f demo-search-proxy-test.yaml up -d
#
version: "3.2"

networks:
   cch-demo:
     ipam:
       config:
         - subnet: 172.24.0.0/16
services:

  demo-search-proxy-test:
    container_name: demo-search-proxy-test
    image: ojbc/demo-search-proxy-test
    build: ./demo-search-proxy-test
    networks:
      - cch-demo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: /apache-certs
        target: "/apache-certs"
      - type: volume
        source: /apache-webroot
        target: "/usr/local/apache2/htdocs"
      - type: volume
        source: /opt/data/search/docker-mounts/demo.search.org
        target: "/opt/data/search/docker-mounts/demo.search.org"
#volumes: 

